# Generated by Django 4.2.2 on 2023-11-24 20:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_overview',
            field=wagtail.fields.RichTextField(blank=True, max_length=1000),
        ),
    ]
