# Generated by Django 4.2.2 on 2023-08-15 20:48

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_about_url_alter_project_code_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=wagtail.fields.RichTextField(),
        ),
    ]
