# Generated by Django 2.2.3 on 2019-07-28 20:38

import core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('image', models.FileField(upload_to=core.managers.create_filename)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('mediafile', models.FileField(upload_to=core.managers.create_filename)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=core.managers.create_filename)),
            ],
            options={
                'db_table': 'periods',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('technologies', models.CharField(blank=True, default='', max_length=256)),
                ('github', models.URLField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=core.managers.create_filename)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('url', models.URLField()),
                ('authors', models.CharField(max_length=512)),
                ('body', models.TextField()),
                ('starred', models.BooleanField(default=False)),
                ('image', models.FileField(upload_to=core.managers.create_filename)),
                ('pdf', models.FileField(upload_to=core.managers.create_filename)),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['-date'],
            },
        ),
    ]
