# Generated by Django 2.2.3 on 2019-07-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
