# Generated by Django 2.0 on 2018-01-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samireland', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('url', models.TextField()),
                ('doi', models.TextField()),
                ('authors', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
