# Generated by Django 2.2.3 on 2019-07-17 09:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('url', models.URLField()),
                ('authors', models.CharField(max_length=512)),
                ('doi', models.CharField(max_length=128)),
                ('abstract', models.TextField()),
                ('body', models.TextField()),
                ('image', models.FileField(upload_to=core.models.create_filename)),
                ('pdf', models.FileField(upload_to=core.models.create_filename)),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
