# Generated by Django 2.0 on 2018-01-14 18:22

from django.db import migrations, models
import samireland.models


class Migration(migrations.Migration):

    dependencies = [
        ('samireland', '0003_mediafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[['web', 'web'], ['python', 'python'], ['other', 'other']], default='web', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='mediafile',
            field=models.FileField(upload_to=samireland.models.MediaFile.create_filename),
        ),
    ]
