# Generated by Django 2.2.3 on 2019-07-17 12:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190717_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('image', models.FileField(upload_to=core.models.create_filename)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-date'],
            },
        ),
    ]
