# Generated by Django 2.2.3 on 2019-07-20 11:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190717_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('period', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=core.models.create_filename)),
            ],
            options={
                'db_table': 'periods',
                'ordering': ['number'],
            },
        ),
    ]
