# Generated by Django 2.2.3 on 2019-07-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutperiod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutPeriod',
            new_name='Period',
        ),
    ]
