# Generated by Django 2.2.3 on 2019-07-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190720_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['-number']},
        ),
        migrations.RenameField(
            model_name='period',
            old_name='period',
            new_name='time',
        ),
    ]
