# Generated by Django 2.2.3 on 2019-07-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190720_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='technologies',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
