# Generated by Django 2.2.3 on 2019-07-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190721_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='github',
        ),
        migrations.RemoveField(
            model_name='period',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
