# Generated by Django 2.2.3 on 2019-07-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190723_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
