# Generated by Django 2.2.3 on 2019-07-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190727_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
