# Generated by Django 2.0 on 2017-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditableText',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('body', models.TextField()),
            ],
        ),
    ]
