# Generated by Django 2.0 on 2018-01-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samireland', '0006_article_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
