# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('url', models.TextField()),
                ('doi', models.TextField()),
                ('authors', models.TextField()),
                ('abstract', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
