# Generated by Django 4.2.2 on 2023-08-28 15:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('text', wagtail.fields.RichTextField(blank=True, max_length=1000)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Must be in the format YYYY=MM', regex='\\d\\d\\d\\d=\\d\\d')])),
                ('end', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Must be in the format YYYY=MM', regex='\\d\\d\\d\\d=\\d\\d')])),
                ('description', wagtail.fields.RichTextField(blank=True, max_length=1000)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='about.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Must be in the format YYYY=MM', regex='\\d\\d\\d\\d=\\d\\d')])),
                ('end', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Must be in the format YYYY=MM', regex='\\d\\d\\d\\d=\\d\\d')])),
                ('description', wagtail.fields.RichTextField(blank=True, max_length=1000)),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subevents', to='about.event')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
