# Generated by Django 4.2.2 on 2023-08-27 13:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('about', '0003_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Must be in the format YYYY=MM', regex='\\d\\d\\d\\d=\\d\\d')])),
                ('end', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Must be in the format YYYY=MM', regex='\\d\\d\\d\\d=\\d\\d')])),
                ('description', wagtail.fields.RichTextField(blank=True, max_length=1000)),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subevents', to='about.event')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
