# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musclegroup',
            old_name='title',
            new_name='name',
        ),
    ]
