# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20160813_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MuscleGroup',
        ),
    ]
