# Generated by Django 4.2.2 on 2023-08-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlepage_delete_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='intro_text',
            new_name='intro',
        ),
    ]
