# Generated by Django 4.2.2 on 2023-08-15 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('articles', '0004_rename_intro_text_articlepage_intro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlesPage',
            new_name='WritingPage',
        ),
    ]
